blank_issues_enabled: true
contact_links:
  - name: â“ Looking for Stylelint?
    url: https://github.com/stylelint/stylelint/issues
    about: Reporting an issue with Stylelint itself? Use the Stylelint issue tracker instead.
