name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    uses: stylelint/.github/.github/workflows/call-release.yml@ce9130c0ded2a1f42fdcb64a0f1f64dd20959795 # 0.5.1
    with:
      publish: true
      publish-npm: false
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
    permissions:
      contents: write
      id-token: write
